### ISSUE TITLE
Using different overlay filters

### ISSUE THREAD

**Issue by Mani-Sadhasivam** [kunalgupta777/OpenCV-Face-Filters#1]
Hello,

I'm trying to reuse your code for applying different filters like leaf crown... But while doing so, the applied part always contains the black background along with the mask. Can you help me to find whats going wrong?

The function is exactly same as `put_hat` and the image used is similar to http://www.stickpng.com/img/icons-logos-emojis/snapchat-filters/snapchat-filter-green-crown 

I'm pretty sure that the image got transparent background.

**Comment by kunalgupta777** [comment]
Hi,
Thanks for pointing out the issue.
Are you using the same version of OpenCV and Python as the script uses?
Also, if you are sure that the image is a PNG type ( which must be for the background to be transparent ),
it would be helpful to see the function you have created.
After that, I might be able to debug the issue.

Regards,
Kunal

**Comment by Mani-Sadhasivam** [comment]
Hi Kunal,

> Are you using the same version of OpenCV and Python as the script uses?

Yes, OpenCV version is 3.2.0 and Python is 2.7

> Also, if you are sure that the image is a PNG type

Yes. You can verify that by downloading the same [image](http://www.stickpng.com/assets/images/580b57fcd9996e24bc43c505.png)

> it would be helpful to see the function you have created.

```python
def put_flower_crown_filter(crown,frame,x,y,w,h):
    face_width = w
    face_height = h
                
    crown_width = face_width+1
    crown_height = int(0.35*face_height)+1
        
    crown = cv2.resize(crown,(crown_width,crown_height))
                                    
    for i in range(crown_height):
        for j in range(crown_width):
            for k in range(3):
                if crown[i][j][k]<235:
                    frame[y+i-int(0.25*face_height)][x+j][k] = crown[i][j][k]
    return frame
```

I hope that the above information is sufficient.

**Comment by Mani-Sadhasivam** [comment]
Hi Kunal,

Did you get time to reproduce the issue?

**Comment by kunalgupta777** [comment]
My exams are going on, I'll be free in some days.
I'll surely get back to the issue.

Regards,
Kunal

**Comment by Akshatha20** [comment]
Hi Kunal,
I tried increasing the size of the cap , but the webcam video runs to slow . Is there a solution for this?

**Comment by kunalgupta777** [comment]
Actually Haar Cascade Classifiers have their limitations.
So either you need to upgrade your system to a more computationally able GPU or switch to a different method of using MobileNet SSD'S
