### ISSUE TITLE
fix : merge pull request

### ISSUE THREAD

**Issue by AFAgarap** [kunalgupta777/OpenCV-Face-Filters#6]
Hello, @kunalgupta777 Perhaps you have only overlooked to merge PR #4 
The purpose of that PR is to call the `download_features.sh` script if the Haar Cascade Filters are not yet in the repository.

**Comment by kunalgupta777** [comment]
I've approved the Merge Request

**Comment by AFAgarap** [comment]
Thanks, @kunalgupta777 ! :)
