### ISSUE TITLE
How did you find this value

### ISSUE THREAD

**Issue by deepanshu2301** [kunalgupta777/OpenCV-Face-Filters#7]
`for i in range(int(0.62857142857*face_height),int(0.62857142857*face_height)+mst_height):
        for j in range(int(0.29166666666*face_width),int(0.29166666666*face_width)+mst_width):
            for k in range(3):
                if mst[i-int(0.62857142857*face_height)][j-int(0.29166666666*face_width)][k] <235:
                    fc[y+i][x+j][k] = mst[i-int(0.62857142857*face_height)][j-int(0.29166666666*face_width)][k]`

How did you find that much precise value buddy ?
(Like 0.62857142857)
Please Explain.

**Comment by kunalgupta777** [comment]
These are just the ratios that best fit the average size of human face. Arrived by trial and error. Referred to some anatomical data as well.
